// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x515151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_chiquito_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Screen1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labalescreentitle = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labalescreentitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labalescreentitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labalescreentitle, 0);
    lv_obj_set_y(ui_labalescreentitle, -200);
    lv_obj_set_align(ui_labalescreentitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labalescreentitle, "DroidMaster");
    lv_obj_set_style_text_color(ui_labalescreentitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labalescreentitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labalescreentitle, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imagenyoutube = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_imagenyoutube, &ui_img_youtube_png);
    lv_obj_set_width(ui_imagenyoutube, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_imagenyoutube, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_imagenyoutube, -118);
    lv_obj_set_y(ui_imagenyoutube, -27);
    lv_obj_set_align(ui_imagenyoutube, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imagenyoutube, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imagenyoutube, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imagenyoutube, 60);

    ui_labelsubscount = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelsubscount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelsubscount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelsubscount, 114);
    lv_obj_set_y(ui_labelsubscount, -30);
    lv_obj_set_align(ui_labelsubscount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelsubscount, "000000");
    lv_obj_set_style_text_color(ui_labelsubscount, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelsubscount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelsubscount, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_checkboxindiedroidnova = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_checkboxindiedroidnova, "Indiedroid Nova");
    lv_obj_set_width(ui_checkboxindiedroidnova, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_checkboxindiedroidnova, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_checkboxindiedroidnova, -224);
    lv_obj_set_y(ui_checkboxindiedroidnova, 87);
    lv_obj_set_align(ui_checkboxindiedroidnova, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_checkboxindiedroidnova, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_checkboxindiedroidnova, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_checkboxindiedroidnova, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_checkboxindiedroidnova, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_checkboxorangepi5 = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_checkboxorangepi5, "Orange Pi 5");
    lv_obj_set_width(ui_checkboxorangepi5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_checkboxorangepi5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_checkboxorangepi5, -255);
    lv_obj_set_y(ui_checkboxorangepi5, 139);
    lv_obj_set_align(ui_checkboxorangepi5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_checkboxorangepi5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_checkboxorangepi5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_checkboxorangepi5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_checkboxorangepi5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_checkboxraspi = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_checkboxraspi, "Raspberry Pi ");
    lv_obj_set_width(ui_checkboxraspi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_checkboxraspi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_checkboxraspi, 80);
    lv_obj_set_x(ui_checkboxraspi, lv_pct(23));
    lv_obj_set_align(ui_checkboxraspi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_checkboxraspi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_checkboxraspi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_checkboxraspi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_checkboxraspi, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_checkboxpizero1 = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_checkboxpizero1, "Orange Pi Zero 3");
    lv_obj_set_width(ui_checkboxpizero1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_checkboxpizero1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_checkboxpizero1, 212);
    lv_obj_set_y(ui_checkboxpizero1, 136);
    lv_obj_set_align(ui_checkboxpizero1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_checkboxpizero1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_checkboxpizero1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_checkboxpizero1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_checkboxpizero1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labellastupdated = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labellastupdated, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labellastupdated, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_labellastupdated, 215);
    lv_obj_set_x(ui_labellastupdated, lv_pct(0));
    lv_obj_set_align(ui_labellastupdated, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labellastupdated, "Last updated: 00:00:00 01/01/2025");
    lv_obj_set_style_text_color(ui_labellastupdated, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labellastupdated, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_labelsubscount, ui_event_labelsubscount, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
