// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_CHECKBOXPIZERO3_H
#define _UI_COMP_CHECKBOXPIZERO3_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT checkboxpizero3
#define UI_COMP_CHECKBOXPIZERO3_CHECKBOXPIZERO3 0
#define _UI_COMP_CHECKBOXPIZERO3_NUM 1
lv_obj_t * ui_checkboxpizero3_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
