// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


// COMPONENT checkboxpizero3

lv_obj_t * ui_checkboxpizero3_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_checkboxpizero3;
    cui_checkboxpizero3 = lv_checkbox_create(comp_parent);
    lv_checkbox_set_text(cui_checkboxpizero3, "Orange Pi Zero 3");
    lv_obj_set_width(cui_checkboxpizero3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_checkboxpizero3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_checkboxpizero3, 127);
    lv_obj_set_y(cui_checkboxpizero3, 136);
    lv_obj_set_align(cui_checkboxpizero3, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_checkboxpizero3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(cui_checkboxpizero3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_checkboxpizero3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_checkboxpizero3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CHECKBOXPIZERO3_NUM);
    children[UI_COMP_CHECKBOXPIZERO3_CHECKBOXPIZERO3] = cui_checkboxpizero3;
    lv_obj_add_event_cb(cui_checkboxpizero3, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_checkboxpizero3, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_checkboxpizero3_create_hook(cui_checkboxpizero3);
    return cui_checkboxpizero3;
}

