// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void calendar_function(lv_event_t * e)
{
	// Your code here
}

void youtube_counter_updater(lv_event_t * e)
{
	// Your code here
}

void screen_is_pressed(lv_event_t * e)
{
	// Your code here
}
